spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:srmdb
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
      show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
server:
  error:
    include-message: always
